### ISSUE TITLE
Create basic schema for describing study metadata

### ISSUE THREAD

**Issue by alamgirmani** [ghga-de/sandbox-metadata#2]

**Comment by KerstenBreuer** [comment]
One DB object will be describing all the metadata for a study. This might include properties like:
- Name of Study
- description
- Patient-Information
- Experiment-Information
- Sequencing-Runs
- File ID of sequencing Runs

**Comment by deepakunni3** [comment]
Example JSON for the metadata can be found here: https://github.com/deepakunni3/ghga-metadata/tree/sandbox/examples

There are 5 object types that are linked to one another:
- Dataset
- Experiment
- Study
- File
- Publication

**Comment by KerstenBreuer** [comment]
@deepakunni3 very cool, that would be perfect for us to start with :)

**Comment by deepakunni3** [comment]
We can keep iterating on the example JSON for our use-cases as well.
